name: Auto PR & Merge

on:
  push:
    branches:
      - develop

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create PR and Merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Clear the GITHUB_TOKEN
        export GITHUB_TOKEN=
        
        # Authenticate with the GitHub CLI
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        
        # Set GitHub CLI as git credential helper
        git config --global credential.https://github.com.helper ''
        git config --global 'credential.https://github.com' '!gh auth git-credential'
        
        # Create a PR from develop to master
        PR_URL=$(gh pr create --base master --head develop --title "Merging changes from develop" --body "Automatic PR for merging changes from develop to master" --draft --json url -q ".url")
        
        # Check if PR can be merged without conflicts
        PR_STATE=$(gh pr view "$PR_URL" --json mergeableState -q ".mergeableState")

        if [[ "$PR_STATE" == "clean" ]]; then
          gh pr merge "$PR_URL" --auto --merge
          echo "Successfully merged the PR!"
        else
          echo "Merge conflicts detected. Manual intervention required."
